export const WORDS = [
  "Accio",
  "Expecto patronum",
  "Wingardium leviosa",
  "Avada kedavra",
  "Expelliarmus",
  "Lumos",
  "Nox",
  "Alohomora",
  "Imperio",
  "Stupefy",
  "Riddikulus",
  "Reducto",
  "Sectumsempra",
  "Sonorus",
  "Tarantallegra",
  "Verdimillious",
  "Bombarda",
  "Confringo",
  "Engorgio",
  "Evanesco",
  "Expulso",
  "Incendio",
  "Legilimens",
  "Obliviate",
  "Petrificus totalus",
  "Prior incantato",
  "Protego",
  "Reparo",
  "Rictusempra",
  "Crucio",
  "Diffindo",
  "Episkey",
  "Finite incantatem",
  "Geminio",
  "Homenum revelio",
  "Impedimenta",
  "Levicorpus",
  "Morsmordre",
  "Orchideous",
  "Portus",
  "Quietus",
  "Relashio",
  "Scourgify",
  "Tergeo",
  "Unbreakable vow",
  "Vulnera sanentur",
  "Waddiwasi",
  "Aparecium",
  "Brackium emendo",
  "Colloportus",
  "Deletrius",
  "Ennervate",
  "Ferula",
  "Glisseo",
  "Herbifors",
  "Incendio",
  "Jelly-legs jinx",
  "Knockback jinx",
  "Langlock",
  "Muffliato",
  "Nebulus",
  "Oculus reparo",
  "Piertotum locomotor",
  "Quidditch",
  "Rennervate",
  "Serpensortia",
  "Transmogrify",
  "Undetectable extension charm",
  "Vipera evanesca",
  "Wingardium leviosa",
  "Xenophilius lovegood",
  "Yaxley",
  "Zonko’s joke shop",
  "Aguamenti",
  "Bubble-head charm",
  "Caterwauling charm",
  "Densaugeo",
  "Erecto",
  "Flagrate",
  "Gouging spell",
  "Hurling hex",
  "Impervius",
  "Jinx",
  "Kreacher",
  "Liberacorpus",
  "Meteolojinx recanto",
  "Nogtail",
  "Obscuro",
  "Peskipiksi pesternomi",
  "Quaffle",
  "Rufus scrimgeour",
  "Silencio",
  "Tutshill tornados",
  "Unguentine",
  "Vera verto",
  "Weasley",
  "Xenophilius",
  "Yew",
  "Zabini",
  "Anteoculatia",
  "Bat-bogey hex",
  "Calvario",
  "Dissendium",
  "Everte statum",
  "Fidelius charm",
  "Geminio",
  "Homenum revelio",
  "Immobulus",
  "Jelly-fingers curse",
  "Knut",
  "Locomotor mortis",
  "Mobiliarbus",
  "Nimbus",
  "Obliteration charm",
  "Piscifors",
  "Quirinus quirrell",
  "Rictusempra",
  "Slugulus eructo",
  "Tentaclifors",
  "Unicorn",
  "Vipera evanesca",
  "Waddiwasi",
  "Xenophilius lovegood",
  "Yew",
]
